# constants for the screen width and height
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800
INITIAL_HP = 10
INITIAL_PLAYER_SPEED = 4
INITIAL_ALLY_BULLET_COOLDOWN = 25
INITIAL_ALLY_BULLET_SPEED = 4
INVINCIBILITY_FRAMES = 20
COLLECTABLE_RADIUS = 10
COLLECTABLE_SPAWN_CHANCE = 100
FPS = 60