# constants for the screen width and height
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 1000
MIN_SCREEN_WIDTH = 1000
MIN_SCREEN_HEIGHT = 800
MAX_SCREEN_WIDTH = 2000
MAX_SCREEN_HEIGHT = 1200
INITIAL_HP = 10
INITIAL_PLAYER_SPEED = 4
INITIAL_ALLY_BULLET_COOLDOWN = 25
INITIAL_ALLY_BULLET_SPEED = 4
INVINCIBILITY_FRAMES = 20
